/// Flutter icons Fitility
/// Copyright (C) 2020 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Fitility
///      fonts:
///       - asset: fonts/Fitility.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class Fitility {
  Fitility._();

  static const _kFontFam = 'Fitility';
  static const _kFontPkg = null;

  static const IconData browser = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gym = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData meal = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData strategic_plan = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData diners_club = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
